### ISSUE TITLE
kontrola katalogu poziadaviek

### ISSUE THREAD

**Issue by kleinMichal** [TIS2016/Anotator-pomenovanych-entit#1]
treba to skontrolovat, upravit vylepsit
na konci dokumentu som pridal alternativu k heslam

**Comment by szendy1** [comment]
**3.9** - jedno slovo v riadku ... 
  1\t  (??Cislo riadku??)    Barrack\t  PER - B\t Link
   2 (??Cislo riadku??)    Obama  PER - I ?Link?
   3   ....                           He         COR - 1 (Coreference)
    ?CisloRiadku- kvoli prehladnosti referencii ? 

TODO:
**1-** suhlasim

**2-** cviciaci to myslim chcel, moze sa urobit nejake tlacitko "Notifications", ktore by otvorilo okienko, kde by sa pisal log vykonanych zmien z casu, v ktorom bol dany uzivatel pripojeny v skupine. 
Napr. Cas, Meno(+funkcia), popis zmeny

**3-** suhlasim, slovo/text moze byt pridany do "skupiny" komentar, ktora bude napr. len podciarkovat 
?.....a ak sa bude dat po prejdeni mysou sa komentar zobrazi v nejakej "bubline" ?

**-Pripominam _Skype_.-**

**Comment by kleinMichal** [comment]
1. opravim zajtra + pridam tam tie cisla riadkov
2. log znie lepsie ako tamto, tak to v tom duchu prepisem
3. znie to dobre
   Zajtra vecer by som to chcel poslat cviciacemu a nasledne zadavatelovi.
   skype meno je: **live:kleinn.michal**

**Comment by pavelpetrovic** [comment]
nezabudnite, prosim, ze treba pouzivat zenhub.com
p.
